### ISSUE TITLE
Detect version conflicts

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgRoutingLayer#10]
Related to #9 it might be also a good idea to 
* **inform** a user, if the pgRouting version is not the latest stable one
* **warn** a user or give an error, if the pgRouting version isn't supported (anymore)

**Comment by cvvergara** [comment]
This plug in only support any 2.x.y version.
that how it was coded originally.

**Comment by cvvergara** [comment]
I'll list the functions on the plug in:

function | new | fixed in | status | use instead
--------------- | ------| --------- | -------------- | -------
alphashape | V2.0 | --  | --  | --
astar            | V2.0 | -- | --  | --
bdAstar        | V2.0 | -- | --  | --
bdDijkstra    | V2.0 | -- | --  | --
dijkstra    | V2.0 | V2.1 | --  | --
drivingDistance | V2.0 | V2.1 | --  | --
kDijkstra(cost)    | V2.0 | V2.2 (with a wrapper) | deprecated | dijkstraCost*
kDijkstra(path) | V2.0 | V2.2 (with a wrapper) | deprecated | dijkstra
ksp | V2.0 | V2.1 | --  | --
trsp(edge) | V2.0 | -- | --  | --
trsp(vertex) | V2.0 | -- | --  | --
trsp(via edges) | V2.1 | -- | --  | --
trsp(via vertex) | V2.1 | -- | --  | --
tsp(euclid)  | V2.0 | -- | --  | --

*Haven't coded in the plugin dijkstraCost yet.

and what I am doing is that if the database has V2.x it will:

1. show in the functions combo the valid functions for that version.
2. show the parameters for that version in each function

dijkstra for V2.0
![version-3](https://cloud.githubusercontent.com/assets/5035290/15988634/01756ad4-301e-11e6-99c5-7cea046e179f.png)
dijstra for version 2.1+
![version-4](https://cloud.githubusercontent.com/assets/5035290/15988636/06a26340-301e-11e6-8896-990273796629.png)

**Comment by cvvergara** [comment]
The results are different also after the export/export merge, due to the fact that there is more information on the results of the query, for example:

For version 2.0
![dijstra-20](https://cloud.githubusercontent.com/assets/5035290/15988686/7988cc18-301f-11e6-8edf-534d584d0d72.png)

For versions 2.1+
![dijstra-21](https://cloud.githubusercontent.com/assets/5035290/15988689/83e76214-301f-11e6-9e77-338fc752e76d.png)

**Comment by cvvergara** [comment]
When pgRouting moves to version 3 then all deprecated functions can be deleted from the plug in.

**Comment by cvvergara** [comment]
Fixed on develop
