### ISSUE TITLE
BBOX section errors

### ISSUE THREAD

**Issue by MarPetra** [pgRouting/pgRoutingLayer#104]
Hello.

Using the GUI I realized that when activating the BBOX option there are always errors:

![bbox](https://user-images.githubusercontent.com/39493413/49692850-99f4fa80-fb29-11e8-90ca-2d8840c39bbd.png)

![bboxerror](https://user-images.githubusercontent.com/39493413/49692849-96617380-fb29-11e8-9c99-d7a7a78de821.png)

**Comment by cvvergara** [comment]
@cayetanobv 
We are using 18.04, and we are using the sample data of the documentation
https://docs.pgrouting.org/2.6/en/sampledata.html

**Comment by cvvergara** [comment]
Ah, now that I remember, I could never figure out how to set SIRD 0 in QGIS

**Comment by cayetanobv** [comment]
Ohh I see it is failing because SRID 0 does not exist as CRS. You need to choose a CRS to use QGIS (default is EPSG:4326 which is WGS84-Gegraphic coordinates).
@cvvergara you can create in QGIS any CRS you want from scratch. If you know CRS parameters (Proj4 definiton string) you can go to "Settings" menu and clic on "custom projections" and create a new CRS (see screenshot):

![image](https://user-images.githubusercontent.com/7315379/49831553-6d90e680-fd94-11e8-9093-9b74513c800c.png)

**Comment by cvvergara** [comment]
https://github.com/qgis/QGIS-Documentation/issues/1724

**Comment by cvvergara** [comment]
We are not having this problem anymore thanks @cayetanobv
