### ISSUE TITLE
Remove experimental flag

### ISSUE THREAD

**Issue by anitagraser** [pgRouting/pgRoutingLayer#118]
pgRoutingLayer is still marked as "experimental" in the metadata and thus on https://plugins.qgis.org/plugins/pgRoutingLayer/. Is there a specific reason to keep it on experimental status? Based on how long it has been around, and how actively you're working on it, I think it should be considered stable. (I usually read "experimental" as "early version, use at your own risk, may corrupt data, might not produce correct results".)

**Comment by cvvergara** [comment]
Hi @anitagraser 
We can remove the experimental flag once we get the 3.0 up we are almost ready
all the 2.x versions needs to be experimental, basically because they use functions that pgRouting 2.x has bugs, so for those this stills apply:
> use at your own risk, may corrupt data, might not produce correct results"

For version 3.0, soon to be released, we can do the removal.

**Comment by cayetanobv** [comment]
Yes, I'm agree. With new version we can remove experimental flag.

**Comment by cvvergara** [comment]
Experimental flag has been removed
