### ISSUE TITLE
Support TRSP same edge case

### ISSUE THREAD

**Issue by sanak** [pgRouting/pgRoutingLayer#6]
**NOTICE: I think that this is not pgrouting itself issue, but pgRoutingLayer issue.**
pgRoutingLayer should support TRSP same edge case.

<pre>
SELECT seq, id1 AS node, id2 AS edge, cost FROM pgr_trsp('
    SELECT id AS id,
        source::int4 AS source,
        target::int4 AS target,
        cost::float8 AS cost 
        FROM edge_table',
    6, 0.25, 6, 0.75, false, false, null);

 seq | node | edge | cost 
-----+------+------+------
   0 |   -1 |    6 |  0.5
(1 row)

SELECT seq, id1 AS path, id2 AS node, id3 AS edge, cost FROM pgr_trspViaEdges('
    SELECT id AS id,
        source::int4 AS source,
        target::int4 AS target,
        cost::float8 AS cost 
        FROM edge_table',
    ARRAY[6,6]::integer[], ARRAY[0.25,0.75]::float8[], false, false, null);

 seq | path | node | edge | cost 
-----+------+------+------+------
   1 |    1 |   -1 |    6 |  0.5
(1 row)
</pre>

**Comment by sanak** [comment]
If the edge is directed, need to care about start/end pos order and result rows count.
<pre>
SELECT seq, id1 AS node, id2 AS edge, cost FROM pgr_trsp('
    SELECT id AS id,
        source::int4 AS source,
        target::int4 AS target,
        cost::float8 AS cost,
        reverse_cost::float8 AS reverse_cost 
        FROM edge_table',
    12, 0.21, 12, 0.68, true, true, null);

 seq | node | edge | cost 
-----+------+------+------
   0 |   -1 |   12 | 0.47
(1 row)

SELECT seq, id1 AS node, id2 AS edge, cost FROM pgr_trsp('
    SELECT id AS id,
        source::int4 AS source,
        target::int4 AS target,
        cost::float8 AS cost,
        reverse_cost::float8 AS reverse_cost 
        FROM edge_table',
    12, 0.68, 12, 0.21, true, true, null);

 seq | node | edge | cost 
-----+------+------+------
   0 |   -1 |   12 | 0.32
   1 |   11 |   13 |    1
   2 |   12 |   15 |    1
   3 |    9 |    9 |    1
   4 |    6 |    8 |    1
   5 |    5 |   10 |    1
   6 |   10 |   12 | 0.21
(7 rows)
</pre>

**Comment by woodbri** [comment]
There are two versions of pgr_trsp,
  1. the uses vertex_id for start and end of route and 
  2. one that uses edge_id and position on edge.

It is not possible to determine direction of travel at a point in space like a vertex. If the vertex is an intersection then there may be multiple possible ways to enter or leave the vertex. It is because of this ambiguity, that we create the edge and position version. If the edge is two way then you can travel either way along that edge to get to or leave that location and if the edge is one way then you only have one direction you can travel. It is also possible to route from two positions on the same edge which might mean your result ONLY include partial travel on that edge only. But if the edge is one way you might have to travel off that edge and cycle around to the other end of that same edge and reenter it to get to you destination.

I strongly recoomend the you ONLY use the edge_id, position version of this command.

**Comment by sanak** [comment]
Okay, thanks for advice!

**Comment by cvvergara** [comment]
The problem is not the GUI its the pgRouting code
