### ISSUE TITLE
Detect the pgRouting version

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgRoutingLayer#9]
I think it would be a good idea to detect the pgRouting version of the database and give the plugin user the ability to show this information, for example by clicking a button

**Comment by cvvergara** [comment]
@dkastl 
I think the changes I made for Version 2.1 hasnt being merged ...
which will need to wait so that what is in master be saved as a tag.
and then make the merge.
If you try what I did, from the connections it detects the version of the database chosen, and accordingly it chooses which functions to display that is because some functions do not exist in 2.0.

**Comment by dkastl** [comment]
Yes, I remember that you made it work with different versions automatically.
My idea for this ticket was to make it visible to the plugin user, which version of pgRouting the database uses.

I think plugin users like visual output, that's why they use the plugin. There can be cases, where someone installed a new version of pgRouting, but the database has the old functions loaded. Having an "info" button in the plugin to show the output of `SELECT pgr_version()` nicely rendered would be convenient.

I just created this ticket to write down the idea and not forget about it.

**Comment by robe2** [comment]
Sounds like a good idea to me especially since people often install the extension binaries and think they are done that they do not need to upgrade the extension in their database.

**Comment by dkastl** [comment]
@robe2 are you talking about me?
You can also get wrong databases with dump files, that load versions of functions, that do not match with the version of PostGIS or pgRouting installed.

Would be nice to have some functionality, that gives a warning not only in the plugin. It's so easy to forget upgrading databases.

**Comment by robe2** [comment]
Just saying :)

**Comment by cvvergara** [comment]
So, here is my opinion:
I don't think we can be responsible of the inactions of users. that is, if the user does not update, its not our problem. He might not be updating so often because other reasons, like its in production, company policies, etc.

But for information I am doing the following:
I have lots of databases with different versions of pgRouting for my tests.

So when selecting a connection I am posting a message indicating which version of pgRouting is installed in that database:
![version-1](https://cloud.githubusercontent.com/assets/5035290/15988520/9347d76c-3019-11e6-984a-bc59e8d3043b.png)
![version-2](https://cloud.githubusercontent.com/assets/5035290/15988521/9b134c6a-3019-11e6-88b2-1913f7f758e1.png)

**Comment by cvvergara** [comment]
fixed on develop
